// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQgYNGgjWOZdv_XFcS0KOOdYPVVnjcvmw',
    appId: '1:390761854844:web:205a571b40709ad8e096f9',
    messagingSenderId: '390761854844',
    projectId: 'evenchucoffee',
    authDomain: 'evenchucoffee.firebaseapp.com',
    storageBucket: 'evenchucoffee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArAFasDYfxgGQ9knn-aszFpaHIq0iB200',
    appId: '1:390761854844:android:3512b207003ddc92e096f9',
    messagingSenderId: '390761854844',
    projectId: 'evenchucoffee',
    storageBucket: 'evenchucoffee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa4d9DdOXjDz0zi6q9D7lsEkmCvxPRmMc',
    appId: '1:390761854844:ios:0b8fe127472605c2e096f9',
    messagingSenderId: '390761854844',
    projectId: 'evenchucoffee',
    storageBucket: 'evenchucoffee.firebasestorage.app',
    iosBundleId: 'com.example.evenChuCoffee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBa4d9DdOXjDz0zi6q9D7lsEkmCvxPRmMc',
    appId: '1:390761854844:ios:0b8fe127472605c2e096f9',
    messagingSenderId: '390761854844',
    projectId: 'evenchucoffee',
    storageBucket: 'evenchucoffee.firebasestorage.app',
    iosBundleId: 'com.example.evenChuCoffee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQgYNGgjWOZdv_XFcS0KOOdYPVVnjcvmw',
    appId: '1:390761854844:web:fe11383a55a0c098e096f9',
    messagingSenderId: '390761854844',
    projectId: 'evenchucoffee',
    authDomain: 'evenchucoffee.firebaseapp.com',
    storageBucket: 'evenchucoffee.firebasestorage.app',
  );
}
